######################################################################
# Automatically generated by qmake (2.01a) Fri Sep 24 15:34:50 2010
######################################################################
QT       += network

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += card.h gameengine.h gamenet.h person.h widget.h
FORMS += widget.ui
SOURCES += card.cpp gameengine.cpp gamenet.cpp main.cpp person.cpp widget.cpp
