#############################################################################
# Makefile for building: CardGame
# Generated by qmake (2.01a) (Qt 4.6.2) on: Mon Oct 25 16:41:09 2010
# Project:  CardGame.pro
# Template: app
# Command: /usr/bin/qmake-qt4 -spec /usr/share/qt4/mkspecs/linux-g++ -unix CONFIG+=debug -o Makefile CardGame.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -g -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -g -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++ -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtNetwork -I/usr/include/qt4/QtGui -I/usr/include/qt4 -I. -I. -I.
LINK          = g++
LFLAGS        = 
LIBS          = $(SUBLIBS)  -L/usr/lib -ldns_sd -lavahi-core -lavahi-client -lQtGui -lQtNetwork -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/bin/qmake-qt4
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = core/player.cpp \
		core/card.cpp \
		core/gameengine.cpp \
		core/gamenet.cpp \
		main.cpp \
		widget.cpp \
		avahi/avahiresolver.cpp \
		avahi/avahiregistrar.cpp \
		avahi/avahibrowser.cpp \
		pistiplayer.cpp \
		batakplayer.cpp moc_gameengine.cpp \
		moc_gamenet.cpp \
		moc_player.cpp \
		moc_widget.cpp \
		moc_avahiresolver.cpp \
		moc_avahiregistrar.cpp \
		moc_avahibrowser.cpp \
		qrc_texture.cpp
OBJECTS       = player.o \
		card.o \
		gameengine.o \
		gamenet.o \
		main.o \
		widget.o \
		avahiresolver.o \
		avahiregistrar.o \
		avahibrowser.o \
		pistiplayer.o \
		batakplayer.o \
		moc_gameengine.o \
		moc_gamenet.o \
		moc_player.o \
		moc_widget.o \
		moc_avahiresolver.o \
		moc_avahiregistrar.o \
		moc_avahibrowser.o \
		qrc_texture.o
DIST          = /usr/share/qt4/mkspecs/common/g++.conf \
		/usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/debug.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		CardGame.pro
QMAKE_TARGET  = CardGame
DESTDIR       = 
TARGET        = CardGame

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET): ui_widget.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: CardGame.pro  /usr/share/qt4/mkspecs/linux-g++/qmake.conf /usr/share/qt4/mkspecs/common/g++.conf \
		/usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/debug.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		/usr/lib/libQtGui.prl \
		/usr/lib/libQtNetwork.prl \
		/usr/lib/libQtCore.prl
	$(QMAKE) -spec /usr/share/qt4/mkspecs/linux-g++ -unix CONFIG+=debug -o Makefile CardGame.pro
/usr/share/qt4/mkspecs/common/g++.conf:
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/debug.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/share/qt4/mkspecs/features/include_source_dir.prf:
/usr/lib/libQtGui.prl:
/usr/lib/libQtNetwork.prl:
/usr/lib/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -spec /usr/share/qt4/mkspecs/linux-g++ -unix CONFIG+=debug -o Makefile CardGame.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/CardGame1.0.0 || $(MKDIR) .tmp/CardGame1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/CardGame1.0.0/ && $(COPY_FILE) --parents core/card.h core/gameengine.h core/gamenet.h core/player.h widget.h avahi/avahiresolver.h avahi/avahiregistrar.h avahi/AvahiRecord.h avahi/avahibrowser.h pistiplayer.h batakplayer.h .tmp/CardGame1.0.0/ && $(COPY_FILE) --parents graphics/texture.qrc .tmp/CardGame1.0.0/ && $(COPY_FILE) --parents core/player.cpp core/card.cpp core/gameengine.cpp core/gamenet.cpp main.cpp widget.cpp avahi/avahiresolver.cpp avahi/avahiregistrar.cpp avahi/avahibrowser.cpp pistiplayer.cpp batakplayer.cpp .tmp/CardGame1.0.0/ && $(COPY_FILE) --parents widget.ui .tmp/CardGame1.0.0/ && (cd `dirname .tmp/CardGame1.0.0` && $(TAR) CardGame1.0.0.tar CardGame1.0.0 && $(COMPRESS) CardGame1.0.0.tar) && $(MOVE) `dirname .tmp/CardGame1.0.0`/CardGame1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/CardGame1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_gameengine.cpp moc_gamenet.cpp moc_player.cpp moc_widget.cpp moc_avahiresolver.cpp moc_avahiregistrar.cpp moc_avahibrowser.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_gameengine.cpp moc_gamenet.cpp moc_player.cpp moc_widget.cpp moc_avahiresolver.cpp moc_avahiregistrar.cpp moc_avahibrowser.cpp
moc_gameengine.cpp: core/card.h \
		pistiplayer.h \
		core/player.h \
		core/gameengine.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) core/gameengine.h -o moc_gameengine.cpp

moc_gamenet.cpp: core/gamenet.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) core/gamenet.h -o moc_gamenet.cpp

moc_player.cpp: core/card.h \
		core/player.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) core/player.h -o moc_player.cpp

moc_widget.cpp: core/card.h \
		core/gameengine.h \
		pistiplayer.h \
		core/player.h \
		core/gamenet.h \
		avahi/avahibrowser.h \
		avahi/AvahiRecord.h \
		avahi/avahiresolver.h \
		avahi/avahiregistrar.h \
		widget.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) widget.h -o moc_widget.cpp

moc_avahiresolver.cpp: avahi/AvahiRecord.h \
		avahi/avahiresolver.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) avahi/avahiresolver.h -o moc_avahiresolver.cpp

moc_avahiregistrar.cpp: avahi/AvahiRecord.h \
		avahi/avahiregistrar.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) avahi/avahiregistrar.h -o moc_avahiregistrar.cpp

moc_avahibrowser.cpp: avahi/AvahiRecord.h \
		avahi/avahibrowser.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) avahi/avahibrowser.h -o moc_avahibrowser.cpp

compiler_rcc_make_all: qrc_texture.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_texture.cpp
qrc_texture.cpp: graphics/texture.qrc \
		graphics/baize.png
	/usr/bin/rcc -name texture graphics/texture.qrc -o qrc_texture.cpp

compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_widget.h
compiler_uic_clean:
	-$(DEL_FILE) ui_widget.h
ui_widget.h: widget.ui
	/usr/bin/uic-qt4 widget.ui -o ui_widget.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_rcc_clean compiler_uic_clean 

####### Compile

player.o: core/player.cpp core/player.h \
		core/card.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o player.o core/player.cpp

card.o: core/card.cpp core/card.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o card.o core/card.cpp

gameengine.o: core/gameengine.cpp core/gameengine.h \
		core/card.h \
		pistiplayer.h \
		core/player.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o gameengine.o core/gameengine.cpp

gamenet.o: core/gamenet.cpp core/gamenet.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o gamenet.o core/gamenet.cpp

main.o: main.cpp widget.h \
		core/card.h \
		core/gameengine.h \
		pistiplayer.h \
		core/player.h \
		core/gamenet.h \
		avahi/avahibrowser.h \
		avahi/AvahiRecord.h \
		avahi/avahiresolver.h \
		avahi/avahiregistrar.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

widget.o: widget.cpp widget.h \
		core/card.h \
		core/gameengine.h \
		pistiplayer.h \
		core/player.h \
		core/gamenet.h \
		avahi/avahibrowser.h \
		avahi/AvahiRecord.h \
		avahi/avahiresolver.h \
		avahi/avahiregistrar.h \
		ui_widget.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o widget.o widget.cpp

avahiresolver.o: avahi/avahiresolver.cpp avahi/avahiresolver.h \
		avahi/AvahiRecord.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o avahiresolver.o avahi/avahiresolver.cpp

avahiregistrar.o: avahi/avahiregistrar.cpp avahi/avahiregistrar.h \
		avahi/AvahiRecord.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o avahiregistrar.o avahi/avahiregistrar.cpp

avahibrowser.o: avahi/avahibrowser.cpp avahi/avahibrowser.h \
		avahi/AvahiRecord.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o avahibrowser.o avahi/avahibrowser.cpp

pistiplayer.o: pistiplayer.cpp pistiplayer.h \
		core/player.h \
		core/card.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o pistiplayer.o pistiplayer.cpp

batakplayer.o: batakplayer.cpp batakplayer.h \
		core/player.h \
		core/card.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o batakplayer.o batakplayer.cpp

moc_gameengine.o: moc_gameengine.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_gameengine.o moc_gameengine.cpp

moc_gamenet.o: moc_gamenet.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_gamenet.o moc_gamenet.cpp

moc_player.o: moc_player.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_player.o moc_player.cpp

moc_widget.o: moc_widget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_widget.o moc_widget.cpp

moc_avahiresolver.o: moc_avahiresolver.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_avahiresolver.o moc_avahiresolver.cpp

moc_avahiregistrar.o: moc_avahiregistrar.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_avahiregistrar.o moc_avahiregistrar.cpp

moc_avahibrowser.o: moc_avahibrowser.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_avahibrowser.o moc_avahibrowser.cpp

qrc_texture.o: qrc_texture.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_texture.o qrc_texture.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

