#############################################################################
# Makefile for building: CardGame
# Generated by qmake (2.01a) (Qt 4.6.2) on: Fri Sep 3 10:40:46 2010
# Project:  CardGame.pro
# Template: app
# Command: /usr/bin/qmake-qt4 -spec /usr/share/qt4/mkspecs/linux-g++ -unix CONFIG+=debug -o Makefile CardGame.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -g -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -g -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++ -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtGui -I/usr/include/qt4 -I. -I.
LINK          = g++
LFLAGS        = 
LIBS          = $(SUBLIBS)  -L/usr/lib -lQtGui -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/bin/qmake-qt4
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		widget.cpp \
		person.cpp \
		card.cpp \
		gameengine.cpp moc_widget.cpp \
		moc_person.cpp \
		moc_gameengine.cpp \
		qrc_application.cpp \
		qrc_graphics.cpp
OBJECTS       = main.o \
		widget.o \
		person.o \
		card.o \
		gameengine.o \
		moc_widget.o \
		moc_person.o \
		moc_gameengine.o \
		qrc_application.o \
		qrc_graphics.o
DIST          = /usr/share/qt4/mkspecs/common/g++.conf \
		/usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/debug.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		CardGame.pro
QMAKE_TARGET  = CardGame
DESTDIR       = 
TARGET        = CardGame

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET): ui_widget.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: CardGame.pro  /usr/share/qt4/mkspecs/linux-g++/qmake.conf /usr/share/qt4/mkspecs/common/g++.conf \
		/usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/debug.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		/usr/lib/libQtGui.prl \
		/usr/lib/libQtCore.prl
	$(QMAKE) -spec /usr/share/qt4/mkspecs/linux-g++ -unix CONFIG+=debug -o Makefile CardGame.pro
/usr/share/qt4/mkspecs/common/g++.conf:
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/debug.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/share/qt4/mkspecs/features/include_source_dir.prf:
/usr/lib/libQtGui.prl:
/usr/lib/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -spec /usr/share/qt4/mkspecs/linux-g++ -unix CONFIG+=debug -o Makefile CardGame.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/CardGame1.0.0 || $(MKDIR) .tmp/CardGame1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/CardGame1.0.0/ && $(COPY_FILE) --parents widget.h person.h card.h gameengine.h .tmp/CardGame1.0.0/ && $(COPY_FILE) --parents application.qrc graphics.qrc .tmp/CardGame1.0.0/ && $(COPY_FILE) --parents main.cpp widget.cpp person.cpp card.cpp gameengine.cpp .tmp/CardGame1.0.0/ && $(COPY_FILE) --parents widget.ui .tmp/CardGame1.0.0/ && (cd `dirname .tmp/CardGame1.0.0` && $(TAR) CardGame1.0.0.tar CardGame1.0.0 && $(COMPRESS) CardGame1.0.0.tar) && $(MOVE) `dirname .tmp/CardGame1.0.0`/CardGame1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/CardGame1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_widget.cpp moc_person.cpp moc_gameengine.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_widget.cpp moc_person.cpp moc_gameengine.cpp
moc_widget.cpp: card.h \
		gameengine.h \
		person.h \
		widget.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) widget.h -o moc_widget.cpp

moc_person.cpp: card.h \
		person.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) person.h -o moc_person.cpp

moc_gameengine.cpp: card.h \
		person.h \
		gameengine.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) gameengine.h -o moc_gameengine.cpp

compiler_rcc_make_all: qrc_application.cpp qrc_graphics.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_application.cpp qrc_graphics.cpp
qrc_application.cpp: application.qrc \
		pics/splash.png
	/usr/bin/rcc -name application application.qrc -o qrc_application.cpp

qrc_graphics.cpp: graphics.qrc \
		graphics/b1fv.png \
		graphics/maca9.png \
		graphics/karopapaz.png \
		graphics/kupakiz.png \
		graphics/sinek2.png \
		graphics/kupa5.png \
		graphics/53.png \
		graphics/karo8.png \
		graphics/b2fh.png \
		graphics/maca3.png \
		graphics/kupavale.png \
		graphics/karo10.png \
		graphics/macakiz.png \
		graphics/sinek8.png \
		graphics/b2fv.png \
		graphics/karoas.png \
		graphics/sinekkiz.png \
		graphics/karo2.png \
		graphics/sinek5.png \
		graphics/kupa6.png \
		graphics/54.png \
		graphics/karo9.png \
		graphics/maca4.png \
		graphics/kupapapaz.png \
		graphics/sinekas.png \
		graphics/karo3.png \
		graphics/kupa7.png \
		graphics/maca5.png \
		graphics/sinek6.png \
		graphics/karo4.png \
		graphics/macapapaz.png \
		graphics/sinek3.png \
		graphics/kupa8.png \
		graphics/maca6.png \
		graphics/karokiz.png \
		graphics/sinek9.png \
		graphics/kupa2.png \
		graphics/sinekpapaz.png \
		graphics/kupa10.png \
		graphics/karo5.png \
		graphics/kupa9.png \
		graphics/kupaas.png \
		graphics/maca7.png \
		graphics/sinek4.png \
		graphics/kupa3.png \
		graphics/karo6.png \
		graphics/maca10.png \
		graphics/maca8.png \
		graphics/macaas.png \
		graphics/b1fh.png \
		graphics/sinek7.png \
		graphics/karovale.png \
		graphics/kupa4.png \
		graphics/sinekvale.png \
		graphics/maca2.png \
		graphics/karo7.png \
		graphics/macavale.png \
		graphics/sinek10.png \
		graphics/back/1.png \
		graphics/back/2.png \
		graphics/back/10.png \
		graphics/back/3.png \
		graphics/back/11.png \
		graphics/back/4.png \
		graphics/back/12.png \
		graphics/back/5.png \
		graphics/back/13.png \
		graphics/back/6.png \
		graphics/back/7.png \
		graphics/back/8.png \
		graphics/back/9.png
	/usr/bin/rcc -name graphics graphics.qrc -o qrc_graphics.cpp

compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_widget.h
compiler_uic_clean:
	-$(DEL_FILE) ui_widget.h
ui_widget.h: widget.ui
	/usr/bin/uic-qt4 widget.ui -o ui_widget.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_rcc_clean compiler_uic_clean 

####### Compile

main.o: main.cpp widget.h \
		card.h \
		gameengine.h \
		person.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

widget.o: widget.cpp widget.h \
		card.h \
		gameengine.h \
		person.h \
		ui_widget.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o widget.o widget.cpp

person.o: person.cpp person.h \
		card.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o person.o person.cpp

card.o: card.cpp card.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o card.o card.cpp

gameengine.o: gameengine.cpp gameengine.h \
		card.h \
		person.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o gameengine.o gameengine.cpp

moc_widget.o: moc_widget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_widget.o moc_widget.cpp

moc_person.o: moc_person.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_person.o moc_person.cpp

moc_gameengine.o: moc_gameengine.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_gameengine.o moc_gameengine.cpp

qrc_application.o: qrc_application.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_application.o qrc_application.cpp

qrc_graphics.o: qrc_graphics.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_graphics.o qrc_graphics.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

